### ISSUE TITLE
running $http in the server returns code 301

### ISSUE THREAD

**Issue by jaypanares** [netanelgilad/angular-meteor-server#3]
Hi, trying to use $http in a service which should return data but I'm receiving a code 301..  I'm connecting to the foursquare api and while the url and params work fine when manually entered in a browser, they don't work when I run it in an $http call.

**Comment by jaypanares** [comment]
running the $http call works fine when run on the client (returns 200), but when I move it into the server it returns a 301

**Comment by netanelgilad** [comment]
Hey @jaypanares,
That happens because when you moved the $http call to the server, it is now using node for http calls. And node http calls works a bit different from a browser http call, in that it doesn't follow redirects. You can read up more is the SO question http://stackoverflow.com/questions/11061118/node-js-requests-returning-301-redirects.
