### ISSUE TITLE
'angular-meteor' module not available on the server on Meteor 1.2

### ISSUE THREAD

**Issue by nickjanssen** [netanelgilad/angular-meteor-server#6]
When you try to upgrade the [example](https://github.com/netanelgilad/angular-server-example) to Meteor 1.2, and make sure the package uses the `angular` and `angular:angular-server` packages (new names since 1.2), it will throw an error.

```
Error: [$injector:modulerr] Failed to instantiate module todomvc due to:
W20151001-15:55:02.115(9)? (STDERR) Error: [$injector:modulerr] Failed to instantiate module angular-meteor due to:
W20151001-15:55:02.115(9)? (STDERR) Error: [$injector:nomod] Module 'angular-meteor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

**Comment by uriva** [comment]
+1

**Comment by uriva** [comment]
FWIW: If I revert to the original packages netanelgilad:angular-server and urigo:angular everything works locally but if I deploy I'm getting an angular error:

Uncaught Error: [$injector:modulerr] Failed to instantiate module appForLunch due to:
Error: [$injector:unpr] Unknown provider: e
http://errors.angularjs.org/1.4.7/$injector/unpr?p0=e
    at http://app-for-lunch.meteor.com/86294ab134117c905b19609e6708f6663e12c1ae.js?meteor_js_resource=true:12:433
    at http://app-for-lunch.meteor.com/86294ab134117c905b19609e6708f6663e12c1ae.js?meteor_js_resource=true:12:19920
    at r (http://app-for-lunch.meteor.com/86294ab134117c905b19609e6708f6663e12c1ae.js?meteor_js_resource=true:12:19090)
    at Object.i [as invoke] (http://app-for-lunch.meteor.com/86294ab134117c905b19609e6708f6663e12c1ae.js?meteor_js_resource=true:12:19427)
    at r (http://app-for-lunch.meteor.com/86294ab134117c905b19609e6708f6663e12c1ae.js?meteor_js_resource=true:12:18478)
    at http://app-for-lunch.meteor.com/86294ab134117c905b19609e6708f6663e12c1ae.js?meteor_js_resource=true:12:18602
    at o (http://app-for-lunch.meteor.com/86294ab134117c905b19609e6708f6663e12c1ae.js?meteor_js_resource=true:12:840)
    at p (http://app-for-lunch.meteor.com/86294ab134117c905b19609e6708f6663e12c1ae.js?meteor_js_resource=true:12:18379)
    at Qe (http://app-for-lunch.meteor.com/86294ab134117c905b19609e6708f6663e12c1ae.js?meteor_js_resource=true:12:20069)
    at s (http://app-for-lunch.meteor.com/86294ab134117c905b19609e6708f6663e12c1ae.js?meteor_js_resource=true:12:7582)
http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=appForLunch&p1=Erro…4117c905b19609e6708f6663e12c1ae.js%3Fmeteor_js_resource%3Dtrue%3A12%3A7582)

**Comment by babsher** [comment]
I think this has something to do with what order the modules get loaded. For example if I move around my module declaration it works sometimes.

**Comment by uriva** [comment]
@netanelgilad any idea why this is happening?

**Comment by redi-absherb** [comment]
I did a bit more digging. Your module definition must be the first file to load. To do this you have to put it and only it in the /lib folder. Meteor will load files here first in alphabetical order.

I think the issue is that its in /lib and not /client/lib

http://docs.meteor.com/#/full/method1rootlevelfolders

**Comment by markoffk** [comment]
+1

I have the same problem after changing package from netanelgilad:angular-server to angular:angular-server. Any new solutions of problem?

**Comment by netanelgilad** [comment]
Hey guys,
Sorry for not getting back to you so long, been busy with other projects (mainly angular-meteor) and now I got some time.
Please notice that you need to depend on the package netanelgilad:angular-server and not angular:angular-server. The package angular:angular-server is just a polyfill for angular on the server side that is used by netanelgilad:angular-server. So please change your dependencies and update me if something is still not working.

**Comment by netanelgilad** [comment]
Please check out version 1.4.4 of netanelgilad:angular-server. Should fix all of your problems..
